# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# This inventory points to an existing Kubernetes cluster deployed by Enterprise-Inference. Only RAG application components will be deployed.
# ============================================================================

[local]
localhost ansible_connection=local

[all]
master1 ansible_host=127.0.0.1

[kube_control_plane]
master1

[kube_node]
master1

[etcd:children]
kube_control_plane

[k8s_cluster:children]
kube_control_plane
kube_node

[k8s_cluster:vars]
ansible_become=true
ansible_user=ubuntu
ansible_connection=local