# Copyright (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: peer-auth
spec:
  mtls:
    mode: STRICT

