# Copyright (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: keycloak-apisix
description: A Helm chart for keycloak apisix used to generate token
version: 0.1.0
