name: ClamAV Antivirus Scan

on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: 'Pull request number'
        required: true
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  clamav-scan:
    name: ClamAV antivirus scan
    runs-on: [innersource.prod.amr.dind]
    container: cache-registry.caas.intel.com/cache/library/python:3.11
    environment: d3
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Install system dependencies and ClamAV
      run: |
        apt-get update
        apt-get install -y clamav clamav-daemon clamav-freshclam
      shell: bash

    - name: Update virus definitions
      run: |
        systemctl stop clamav-freshclam || true
        freshclam --quiet --no-warnings
        echo "Virus definitions updated successfully"
      shell: bash

    - name: Run ClamAV scan
      run: |
        echo "Starting antivirus scan of repository..."
        clamscan -r --infected --bell --exclude-dir=.git . > clamav-report.txt 2>&1
        scan_result=$?
        
        echo "Scan completed with exit code: $scan_result"
        cat clamav-report.txt
        
        if [ $scan_result -eq 1 ]; then
          echo "Issues detected! Check the scan results above."
          exit 1
        elif [ $scan_result -eq 0 ]; then
          echo "No issues detected. Repository is clean."
        else
          echo "Scanner encountered an error (exit code: $scan_result)"
          exit 1
        fi
      shell: bash
      continue-on-error: false

    - name: Upload ClamAV results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: clamav-antivirus-report
        path: clamav-report.txt
        retention-days: 30
