name: Linter

on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: 'Pull request number'
        required: true
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  lint:
    runs-on: [innersource.prod.amr.dind]
    container: cache-registry.caas.intel.com/cache/library/python:3.11
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print YAML Lint Config
        run: cat .github/linters/.yaml-lint.yml

      - name: Super-Linter
        uses: super-linter/super-linter/slim@v6.8.0
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          BASH_SEVERITY: error
          FILTER_REGEX_EXCLUDE: ".*/templates/.*\\.yaml|.*/config/manifests/.*\\.yaml|.*/gmc-router\\.yaml|\\.github/.*"
          VALIDATE_YAML: true
          VALIDATE_PYTHON_RUFF: true
          HADOLINT_CONFIG_FILE: .github/linters/.hadolint.yaml
          VALIDATE_DOCKERFILE_HADOLINT: true
          GITHUB_TOKEN: ${{ github.token }}                    
          DEFAULT_BRANCH: main
